# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20170707_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_checkin',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date_checkout',
        ),
    ]
